/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ApiPublicCronDailySyncRouteImport } from './routes/api/public/cron/daily-sync'

const ApiPublicCronDailySyncRoute = ApiPublicCronDailySyncRouteImport.update({
  id: '/api/public/cron/daily-sync',
  path: '/api/public/cron/daily-sync',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/api/public/cron/daily-sync': typeof ApiPublicCronDailySyncRoute
}
export interface FileRoutesByTo {
  '/api/public/cron/daily-sync': typeof ApiPublicCronDailySyncRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/api/public/cron/daily-sync': typeof ApiPublicCronDailySyncRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/api/public/cron/daily-sync'
  fileRoutesByTo: FileRoutesByTo
  to: '/api/public/cron/daily-sync'
  id: '__root__' | '/api/public/cron/daily-sync'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ApiPublicCronDailySyncRoute: typeof ApiPublicCronDailySyncRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/api/public/cron/daily-sync': {
      id: '/api/public/cron/daily-sync'
      path: '/api/public/cron/daily-sync'
      fullPath: '/api/public/cron/daily-sync'
      preLoaderRoute: typeof ApiPublicCronDailySyncRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  ApiPublicCronDailySyncRoute: ApiPublicCronDailySyncRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
